#!/usr/bin/python

import time, logging
import ConfigParser, string
import signal, Queue
import textwrap

import tabnanny
import sys, os

import tweepy

options = { "catch_hup" : True,
            "log_debug" : False,
            "text_wrap" : True,
            # value in minutes
            "update_frequency" : 5 }

class MalformedKeyFile(Exception):
    def __init__(self):
        pass

class KeyFileNotFound(IOError):
    def __init__(self):
        pass

def setup_logging(name, log_debug=False):
    logger = logging.getLogger(name)
    if log_debug:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)
    # Create a file handler which even logs debug messages
    fh = logging.FileHandler(name + ".log")
    fh.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    fh.setFormatter(formatter)
    logging.getLogger('').addHandler(fh)
    return logger

def handler(signum, frame):
    local_logger = logging.getLogger("gribbit.handler")
    local_logger.info("Signal handler called, signum %i", signum)
    wakeup_queue.put(signum)

def apply_config(cfg, logger):
    # Process debug logging first so the other options get caught
    if cfg.has_option("gribbit", "log_debug"):
        logger.debug("Processing [%s, %s]" % ("gribbit", "log_debug"))
        options["log_debug"] = cfg.getboolean("gribbit", "log_debug")
        logger.info("Set options.log_debug to " + options["log_debug"].__str__())
        if options["log_debug"]:
            logger.setLevel(logging.DEBUG)
        else:
            logger.setLevel(logging.INFO)

    # Now do the others
    for section in cfg.sections():
        for option in cfg.options(section):
            if section != "gribbit" or option != "log_debug":
                logger.debug("Processing [%s, %s]" % (section, option))
            if section == "gribbit" and option == "catch_hup":
                options["catch_hup"] = cfg.getboolean(section, option)
                logger.info("Set options.catch_hup to " + options["catch_hup"].__str__())
            if section == "gribbit" and option == "text_wrap":
                options["text_wrap"] = cfg.getboolean(section, option)
                logger.info("Set options.text_wrap to " + options["text_wrap"].__str__())
            if section == "updates" and option == "frequency":
                options["update_frequency"] = cfg.getint(section, option)
                logger.info("Set options.update_frequency to %i", options["update_frequency"])


def load_config(logger):
    cfg = ConfigParser.SafeConfigParser()
    cfgfiles = cfg.read(["gribbit.cfg", os.path.expanduser("~/.gribbit.cfg")])
    if len(cfgfiles) > 0:
        logger.info("Parsed config from " + string.join(cfgfiles, ', '))
        apply_config(cfg, logger)
    else:
        logger.info("No config files to load, using defaults")
        print "No config files to load, using defaults"

def load_keys(logger):
    cfg = ConfigParser.SafeConfigParser()
    cfgfiles = cfg.read("gribbit.keys")
    if len(cfgfiles) > 0:
        logger.info("Reading gribbit.keys")
        if cfg.has_section("keys"):
            auth = tweepy.OAuthHandler(cfg.get("keys", "consumer_key"), cfg.get("keys", "consumer_secret"))
            auth.set_access_token(cfg.get("keys", "access_token"), cfg.get("keys", "access_token_secret"))
            api = tweepy.API(auth)
            logger.info("Loaded keys from gribbit.keys")
        else:
            logger.critical("Malformed gribbit.keys file")
            raise MalformedKeyFile
    else:
        logger.critical("No gribbit.keys file")
        raise KeyFileNotFound

    return api

logger = setup_logging("gribbit", log_debug=options["log_debug"])
load_config(logger)

try:
    api = load_keys(logger)
except MalformedKeyFile:
    print "Looks like gribbit.keys isn't correctly written. Please check"
    print "the documentation for the right format."
    sys.exit(1)
except KeyFileNotFound:
    print "Couldn't read gribbit.keys - please check the documentation for what to do."
    sys.exit(2)

wakeup_queue = Queue.Queue()
logger.debug("Created queue")

MINUTE=60
old_date = ""
last_id = -1

if options["catch_hup"]:
    logger.debug("Installing HUP handler")
    old_handler = signal.signal(signal.SIGHUP, handler)

indent = " " * 17
w = textwrap.TextWrapper(width=92, subsequent_indent=indent)

# If we hit an error at this stage, assume invalid keys. Could still be Twitter down...
try:
    tl = api.friends_timeline()
except tweepy.error.TweepError:
    logger.critical("API error trying to update. Are your keys valid? Is Twitter up?")
    print "Error trying to get tweets. Possible causes - invalid keys, Twitter has gone down..."
    sys.exit(3)

while 1:
    logger.debug("Processing %i tweets", len(tl))

    tl.reverse()
    for tweet in tl:
        new_date = tweet.created_at.strftime("%Y/%m/%d")
        if new_date != old_date:
            logger.info("Date changed from '%s' to '%s'", old_date, new_date)
            time_format = "%m/%d %H:%M:%S"
            old_date = new_date
        else:
            time_format = "      %H:%M:%S"
        text = "%s - %s: %s" % (tweet.created_at.strftime(time_format), tweet.user.screen_name, tweet.text)
        if options["text_wrap"]:
            for line in w.wrap(text):
                print line
        else:
            print text
        last_id = tweet.id

    try:
        item = wakeup_queue.get(True, options["update_frequency"] * MINUTE)
        # If we reach this line we got a signal
        if hasattr(item, "__str__"):
            logger.info("Got signal %s", item.__str__())
        else:
            logger.info("Got signal, item has no string rep")
        logger.info("Reloading config file")
        load_config(logger)
        wakeup_queue.task_done()
    except Queue.Empty:
        # This is the usual case - timeout
        pass
    except KeyboardInterrupt:
        print "Ctrl-C detected"
        logger.warn("Ctrl-C detected")
        break

    logger.debug("Requesting tweets since %i", last_id)
    try:
        tl = api.friends_timeline(since_id=last_id, count=1000)
    except tweepy.error.TweepError:
        logger.warning("Got API error updating timeline; stalling to see if Twitter recovers.")
        tl = []

if options["catch_hup"]:
    # Restore old handler
    logger.debug("Restoring old HUP handler")
    signal.signal(signal.SIGHUP, old_handler)
